// <auto-generated />
namespace MVC_Garage_2._0.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class To2_1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(To2_1));
        
        string IMigrationMetadata.Id
        {
            get { return "201710261100365_To2_1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
