// <auto-generated />
namespace MVC_Garage_2._0.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class StartWithCleanDb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(StartWithCleanDb));
        
        string IMigrationMetadata.Id
        {
            get { return "201710251353403_StartWithCleanDb"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
